import { ThumbnailDesign } from "@/types/thumbnail/ThumbnailDesign";
import { DEFAULT_CANVAS_SIZE } from "@/consts/thumbnail/defaults";
import { uuid } from "@/utils/thumbnail/uuid";

export const vsMatchTemplate = (fontFamily = "Montserrat"): ThumbnailDesign => {
  const canvas = { ...DEFAULT_CANVAS_SIZE };
  const W = canvas.width;
  const H = canvas.height;
  const bandHeight = 100;

  return {
    id: "vs-match",
    name: "VS Match",
    canvasSize: canvas,
    background: { type: "split", left: "#D9482F", right: "#E7B127", angle: 0 },
    elements: [
      {
        id: uuid(),
        type: "shape",
        shape: "rect",
        templateRole: "topBand",
        name: "Top band",
        x: 0,
        y: 0,
        width: W,
        height: bandHeight,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        fill: "#FFFFFF",
      },
      {
        id: uuid(),
        type: "shape",
        shape: "rect",
        templateRole: "bottomBand",
        name: "Bottom band",
        x: 0,
        y: H - bandHeight,
        width: W,
        height: bandHeight,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        fill: "#FFFFFF",
      },
      {
        id: uuid(),
        type: "character",
        templateRole: "leftCharacter",
        name: "Left character",
        x: 40,
        y: bandHeight + 10,
        width: 540,
        height: 500,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        characterId: "1293",
        alt: 0,
        imageType: "main",
        flipX: false,
      },
      {
        id: uuid(),
        type: "character",
        templateRole: "rightCharacter",
        name: "Right character",
        x: 700,
        y: bandHeight + 10,
        width: 540,
        height: 500,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        characterId: "1293",
        alt: 1,
        imageType: "main",
        flipX: true,
      },
      {
        id: uuid(),
        type: "text",
        templateRole: "leftPlayerName",
        name: "Left player name",
        text: "Player X",
        x: 40,
        y: 18,
        width: 600,
        height: 70,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        fontFamily,
        fontSize: 64,
        fontStyle: "bold",
        fill: "#000000",
        align: "center",
        autoFit: true,
      },
      {
        id: uuid(),
        type: "text",
        templateRole: "rightPlayerName",
        name: "Right player name",
        text: "Player Y",
        x: W - 640,
        y: 18,
        width: 600,
        height: 70,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        fontFamily,
        fontSize: 64,
        fontStyle: "bold",
        fill: "#000000",
        align: "center",
        autoFit: true,
      },
      {
        id: uuid(),
        type: "text",
        templateRole: "leftBracketInfo",
        name: "Left bracket info",
        text: "Winners",
        x: 40,
        y: H - bandHeight + 22,
        width: 600,
        height: 60,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        fontFamily,
        fontSize: 56,
        fontStyle: "bold",
        fill: "#000000",
        align: "center",
      },
      {
        id: uuid(),
        type: "text",
        templateRole: "rightBracketInfo",
        name: "Right bracket info",
        text: "Round 1",
        x: W - 640,
        y: H - bandHeight + 22,
        width: 600,
        height: 60,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        fontFamily,
        fontSize: 56,
        fontStyle: "bold",
        fill: "#000000",
        align: "center",
      },
      {
        id: uuid(),
        type: "text",
        templateRole: "vsLabel",
        name: "VS",
        text: "VS",
        x: W / 2 - 90,
        y: H / 2 - 70,
        width: 180,
        height: 140,
        rotation: 0,
        opacity: 1,
        visible: true,
        locked: false,
        fontFamily,
        fontSize: 120,
        fontStyle: "italic bold",
        fill: "#FFFFFF",
        stroke: "#000000",
        strokeWidth: 8,
        align: "center",
      },
    ],
  };
};
