export enum LayoutPlaceholder {
  PLAYER_PLACEMENT = "<🥇>",
  TOURNAMENT_NAME = "<📝>",
  EVENT_NAME = "<🎮>",
  TOURNAMENT_DATE = "<📅>",
  TOURNAMENT_LOCATION = "<🌍>",
  TOURNAMENT_CITY = "<🏙️>",
  TOURNAMENT_STATE = "<🏙️🏙️>",
  TOURNAMENT_COUNTRY = "<🏙️🏙️🏙️>",
  ENTRANTS = "<👥>",
  PLAYER_NAME = "<👤>",
  PLAYER_TAG = "<🏷️>",
  PLAYER_PREFIX = "<🎭>",
  PLAYER_TWITTER = "<🐦>",
}
