export enum DesignPlaceholder {
  PLAYER_PLACEMENT = "<🥇>",
  PLAYER_COUNTRY = "<🎌>",
  TOURNAMENT_NAME = "<📝>",
  EVENT_NAME = "<🎮>",
  TOURNAMENT_DATE = "<📅>",
  TOURNAMENT_LOCATION = "<🌍>",
  TOURNAMENT_CITY = "<🏙️>",
  TOURNAMENT_STATE = "<🏙️🏙️>",
  TOURNAMENT_COUNTRY = "<🏙️🏙️🏙️>",
  TOURNAMENT_URL = "<🔗>",
  ENTRANTS = "<👥>",
  PLAYER_NAME = "<👤>",
  PLAYER_TAG = "<🏷️>",
  PLAYER_PREFIX = "<🎭>",
  PLAYER_TWITTER = "<🐦>",
}

export const PlaceholderLabel: Record<DesignPlaceholder, string> = {
  [DesignPlaceholder.PLAYER_PLACEMENT]: "Player Placement",
  [DesignPlaceholder.PLAYER_COUNTRY]: "Player Country",
  [DesignPlaceholder.TOURNAMENT_NAME]: "Tournament Name",
  [DesignPlaceholder.EVENT_NAME]: "Event Name",
  [DesignPlaceholder.TOURNAMENT_DATE]: "Tournament Date",
  [DesignPlaceholder.TOURNAMENT_LOCATION]:
    "Tournament Location (City, State, Country)",
  [DesignPlaceholder.TOURNAMENT_CITY]: "Tournament City",
  [DesignPlaceholder.TOURNAMENT_STATE]: "Tournament State",
  [DesignPlaceholder.TOURNAMENT_COUNTRY]: "Tournament Country",
  [DesignPlaceholder.TOURNAMENT_URL]: "Tournament URL",
  [DesignPlaceholder.ENTRANTS]: "# of Entrants",
  [DesignPlaceholder.PLAYER_NAME]: "Player Name (w/ Prefix)",
  [DesignPlaceholder.PLAYER_TAG]: "Player Tag",
  [DesignPlaceholder.PLAYER_PREFIX]: "Player Prefix",
  [DesignPlaceholder.PLAYER_TWITTER]: "Twitter Handle",
};
